### ISSUE TITLE
How to deal with dimension mismatch?

### ISSUE THREAD

**Issue by ShunLu91** [changlin31/DNA#12]
Firstly, thanks for your nice work!
However, the dimension mismatch occurs when the student model blocks' output is changing but the output dimension of teacher model is fixed and I haven't found more details about this issue in your paper. Especially the channel, did you just take the first N channels directly?
So could you please tell me how to deal with it?

**Comment by CuriousCat-7** [comment]
I want to ask the same question, as the table shows in:
![image](https://user-images.githubusercontent.com/17199271/82198182-89f06580-992e-11ea-86f8-0396466bc282.png)
the channel numbers of the teacher and the student are different.

**Comment by changlin31** [comment]
Hi @ShunLu91 and @CuriousCat-7 ,

We simply increase the input and output channels of the student block to the same number with the teacher block, and keep the middle layers channel number unchanged. We notice no obvious performance drop when reducing the input and output channel of each block when retraining.

You can also add 1x1 convolution layers to project the feature map, like the referenced paper, but we chose the aforementioned simpler way to implement it. We will soon release our supernet training code.

**Comment by wangq95** [comment]
@changlin31 Hi, I am also very concerned about this issue. Maybe you directly use zero-padding for the channel dimension,  to ensure the same dimension of features?

**Comment by changlin31** [comment]
Hi @wangq95 , in fact we use the same input and output channels for the student block and the teacher block during supernet training. As the searching code has been released now, you can check for details.
