### ISSUE TITLE
File "process_potential.py", line 211, in main     sorted_model.append(model_pool[block_idx][top_idx].copy())

### ISSUE THREAD

**Issue by Kyrie10favor** [changlin31/DNA#15]
Hello, I used my own dataset, which has 10 categories. I modified "**`initialize/ data.yaml`** ”And "**`initialize / train_ pipeline.yaml`** "
After completing step I, I get five "**`potential-*. yaml`**" files, and then run "**`Python process_ potential.py`** ”However, the error message is as follows:
` Traceback (most recent call last):`
  `File "process_potential.py", line 333, in <module>`
   ` main()`
 `File "process_potential.py", line 211, in main`
    `sorted_model.append(model_pool[block_idx][top_idx].copy())`
`IndexError: list index out of range `

How can I solve this problem?thank u.

**Comment by changlin31** [comment]
Hi @liuyuankai666 , sorry for not covering this in README. To run the search code, you should modify the `layer_cfgs` and `block_cfgs` and other settings in `process_potential.py`. If you didn't change the default `self.block_cfgs` for `StudentSupernet` in `student_supernet.py`, try this:

```
layer_cfgs = [
    [2, 4, 4, 4, 4, 1]
]
block_cfgs = [
    [24, 24, 2, 2],
    [40, 40, 2, 4],
    [80, 80, 2, 4],
    [112, 112, 1, 4],
    [192, 192, 2, 4],
    [320, 320, 1, 1]
]
```
(If you are using different candidate operations or number of channels, you may also need to re-calculate the FLOPS table in `process_potential.py`)
