### ISSUE TITLE
# Is the get_model_complexity_info function called in any document?

### ISSUE THREAD

**Issue by janezzzz** [changlin31/DNA#16]
Hi, I'm a little confused with the use of flops_counter. Is this function used for calculating the number of FLOPs and parameters after training? Or to provide some constraints during the searching? Thanks!

**Comment by changlin31** [comment]
Hi @janezzzz ,
We only call `get_model_parameters_number` in `process_potential.py` to calculate the parameters during searching. The look-up table of FLOPS in the code of `process_potential.py` is pre-calculated using `flops_counter.py` and recorded manually to prevent repeated forwarding during search.
