### ISSUE TITLE
The size of the search space

### ISSUE THREAD

**Issue by zhengjian2322** [changlin31/DNA#28]
Hi, I really enjoy your paper!
I have a question, why the size of the search space in section 4.1 is  2×10e17?

**Comment by changlin31** [comment]
Hi,

Given num_op = 6, search space is calculated by (num_op ** num_layer). By adding the search space of three different supernets, we have:

block 1 search space: 6**2 + 6**3 + 6**2 = 288
block 2 search space: 6**2 + 6**3 + 6**4 = 1548
block 3 search space: 6**2 + 6**3 + 6**4 = 1548
block 4 search space: 6**3 + 6**4 + 6**4 = 2808
block 5 search space: 6**4+ 6**5 + 6**5 = 16848
block 6 search space: 6

total search space: 288 * 1548 * 1548 * 2808 * 16848 * 6 = 195898498887057408, which is about 2×10^17.

**Comment by zhengjian2322** [comment]
Thank you very much!
But I have another question why the number of partial models is about 10^4 in each cell?
